"""added post created on

Revision ID: a2ee3d6c2127
Revises: e33348dd5dfb
Create Date: 2020-04-02 15:54:00.290690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ee3d6c2127'
down_revision = 'e33348dd5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_on')
    # ### end Alembic commands ###
